DROP TABLE IF EXISTS SHADOW;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PRIME_ITEM;
DROP TABLE IF EXISTS PRIME_CARD;
CREATE TABLE USERS
(
    uid VARCHAR(20),
    username VARCHAR(20) NOT NULL,
    usertype VARCHAR(10) NOT NULL DEFAULT "NORMAL",
    start_date DATETIME,
    PRIMARY KEY(uid),
    CHECK(TYPE IN ("ADMIN","NORMAL"))
);

CREATE TABLE SHADOW (
    id INT PRIMARY KEY AUTO_INCREMENT,
    uid VARCHAR(20),
    FOREIGN KEY (uid)
        REFERENCES USERS (uid)
        ON DELETE CASCADE ON UPDATE CASCADE,
    PASSWORD VARCHAR(200) UNIQUE NOT NULL
);

CREATE TABLE PRIME_CARD(
    title varchar(100),
    image_url TEXT NOT NULL,
    PRIMARY KEY(title)
);

CREATE TABLE PRIME_ITEM (
    id INT PRIMARY KEY AUTO_INCREMENT,
    image_url TEXT NOT NULL,
    title TEXT NOT NULL,
    head TEXT NOT 
    body TEXT NOT NULL,
    tail TEXT NOT NULL,
    link TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    FOREIGN KEY (category)
        REFERENCES PRIME_CARD (title)
        ON DELETE CASCADE ON UPDATE CASCADE
);
